apiVersion: v1
kind: ConfigMap
metadata:
  name: docurgent-config
  namespace: docurgent
data:
  # Redis
  redis-host: "redis-service"
  redis-port: "6379"
  
  # MinIO
  minio-endpoint: "minio-service:9000"
  minio-bucket: "docurgent-files"
  
  # SMTP
  smtp-host: "smtp.gmail.com"
  smtp-port: "587"
  smtp-from: "noreply@docurgent.com"
  
  # Application
  app-name: "DocUrgent"
  environment: "production"
  debug: "False"
  
  # CORS
  cors-origins: "https://docurgent.com,https://app.docurgent.com"
